version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '${PORT_DB}:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - admi-bd
  adminer:
    container_name: adminer
    depends_on:
      - db
    image: adminer:standalone
    restart: always
    ports:
      - ${PORT_ADM}:8080
    networks:
      - admi-bd
networks:
  admi-bd:
    name: admi-bd
    driver: bridge
    #external: true
